#include <avr/pgmspace.h>
#include <stdint.h>

// define colors (BGR)
#define BLACK 0x0000
#define BLUE 0x001F
#define RED 0xF800
#define GREEN 0x07E0
#define YELLOW 0xFFE0
#define BROWN 0x7B00
#define ORANGE 0xFD20
#define PURPLE 0xF81F


// not revealed, not selected
const uint16_t PROGMEM emptyUnrevealedGrid[16][16] = {
    { BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK },
    { BLACK, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, BLACK },
    { BLACK, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, BLACK },
    { BLACK, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, BLACK },
    { BLACK, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, BLACK },
    { BLACK, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, BLACK },
    { BLACK, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, BLACK },
    { BLACK, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, BLACK },
    { BLACK, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, BLACK },
    { BLACK, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, BLACK },
    { BLACK, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, BLACK },
    { BLACK, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, BLACK },
    { BLACK, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, BLACK },
    { BLACK, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, BLACK },
    { BLACK, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, BLACK },
    { BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK },
};

// not revealed, but selected
const uint16_t PROGMEM emptyUnrevealedSelectedGrid[16][16] = {
    { BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK },
    { BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK },
    { BLACK, BLACK, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, BLACK, BLACK },
    { BLACK, BLACK, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, BLACK, BLACK },
    { BLACK, BLACK, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, BLACK, BLACK },
    { BLACK, BLACK, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, BLACK, BLACK },
    { BLACK, BLACK, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, BLACK, BLACK },
    { BLACK, BLACK, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, BLACK, BLACK },
    { BLACK, BLACK, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, BLACK, BLACK },
    { BLACK, BLACK, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, BLACK, BLACK },
    { BLACK, BLACK, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, BLACK, BLACK },
    { BLACK, BLACK, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, BLACK, BLACK },
    { BLACK, BLACK, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, BLACK, BLACK },
    { BLACK, BLACK, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, BLACK, BLACK },
    { BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK },
    { BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK },
};

// revealed empty grid, not selected
const uint16_t PROGMEM emptyRevealedGrid[16][16] = {
    { BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK },
    { BLACK, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BLACK },
    { BLACK, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BLACK },
    { BLACK, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BLACK },
    { BLACK, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BLACK },
    { BLACK, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BLACK },
    { BLACK, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BLACK },
    { BLACK, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BLACK },
    { BLACK, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BLACK },
    { BLACK, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BLACK },
    { BLACK, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BLACK },
    { BLACK, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BLACK },
    { BLACK, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BLACK },
    { BLACK, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BLACK },
    { BLACK, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BLACK },
    { BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK },
};

// revealed empty grid, but selected 
const uint16_t PROGMEM emptyRevealedSelectedGrid[16][16] = {
    { BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK },
    { BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK },
    { BLACK, BLACK, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BLACK, BLACK },
    { BLACK, BLACK, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BLACK, BLACK },
    { BLACK, BLACK, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BLACK, BLACK },
    { BLACK, BLACK, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BLACK, BLACK },
    { BLACK, BLACK, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BLACK, BLACK },
    { BLACK, BLACK, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BLACK, BLACK },
    { BLACK, BLACK, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BLACK, BLACK },
    { BLACK, BLACK, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BLACK, BLACK },
    { BLACK, BLACK, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BLACK, BLACK },
    { BLACK, BLACK, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BLACK, BLACK },
    { BLACK, BLACK, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BLACK, BLACK },
    { BLACK, BLACK, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BLACK, BLACK },
    { BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK },
    { BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK },
};

// revealed, 1 mine in proximity, not selected
const uint16_t PROGMEM number1Grid[16][16] = {
    { BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK },
    { BLACK, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BLACK },
    { BLACK, BROWN, BROWN, BROWN, BROWN, BROWN, BLUE, BLUE, BLUE, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BLACK },
    { BLACK, BROWN, BROWN, BROWN, BROWN, BROWN, BLUE, BLUE, BLUE, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BLACK },
    { BLACK, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BLUE, BLUE, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BLACK },
    { BLACK, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BLUE, BLUE, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BLACK },
    { BLACK, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BLUE, BLUE, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BLACK },
    { BLACK, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BLUE, BLUE, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BLACK },
    { BLACK, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BLUE, BLUE, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BLACK },
    { BLACK, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BLUE, BLUE, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BLACK },
    { BLACK, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BLUE, BLUE, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BLACK },
    { BLACK, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BLUE, BLUE, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BLACK },
    { BLACK, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BLUE, BLUE, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BLACK },
    { BLACK, BROWN, BROWN, BROWN, BROWN, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BROWN, BROWN, BROWN, BROWN, BLACK },
    { BLACK, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BLACK },
    { BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK },
};

// revealed, 1 mine in proximity, but selected
const uint16_t PROGMEM number1SelectedGrid[16][16] = {
    { BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK },
    { BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK },
    { BLACK, BLACK, BROWN, BROWN, BROWN, BROWN, BLUE, BLUE, BLUE, BROWN, BROWN, BROWN, BROWN, BROWN, BLACK, BLACK },
    { BLACK, BLACK, BROWN, BROWN, BROWN, BROWN, BLUE, BLUE, BLUE, BROWN, BROWN, BROWN, BROWN, BROWN, BLACK, BLACK },
    { BLACK, BLACK, BROWN, BROWN, BROWN, BROWN, BROWN, BLUE, BLUE, BROWN, BROWN, BROWN, BROWN, BROWN, BLACK, BLACK },
    { BLACK, BLACK, BROWN, BROWN, BROWN, BROWN, BROWN, BLUE, BLUE, BROWN, BROWN, BROWN, BROWN, BROWN, BLACK, BLACK },
    { BLACK, BLACK, BROWN, BROWN, BROWN, BROWN, BROWN, BLUE, BLUE, BROWN, BROWN, BROWN, BROWN, BROWN, BLACK, BLACK },
    { BLACK, BLACK, BROWN, BROWN, BROWN, BROWN, BROWN, BLUE, BLUE, BROWN, BROWN, BROWN, BROWN, BROWN, BLACK, BLACK },
    { BLACK, BLACK, BROWN, BROWN, BROWN, BROWN, BROWN, BLUE, BLUE, BROWN, BROWN, BROWN, BROWN, BROWN, BLACK, BLACK },
    { BLACK, BLACK, BROWN, BROWN, BROWN, BROWN, BROWN, BLUE, BLUE, BROWN, BROWN, BROWN, BROWN, BROWN, BLACK, BLACK },
    { BLACK, BLACK, BROWN, BROWN, BROWN, BROWN, BROWN, BLUE, BLUE, BROWN, BROWN, BROWN, BROWN, BROWN, BLACK, BLACK },
    { BLACK, BLACK, BROWN, BROWN, BROWN, BROWN, BROWN, BLUE, BLUE, BROWN, BROWN, BROWN, BROWN, BROWN, BLACK, BLACK },
    { BLACK, BLACK, BROWN, BROWN, BROWN, BROWN, BROWN, BLUE, BLUE, BROWN, BROWN, BROWN, BROWN, BROWN, BLACK, BLACK },
    { BLACK, BLACK, BROWN, BROWN, BROWN, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BROWN, BROWN, BROWN, BLACK, BLACK },
    { BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK },
    { BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK },
};

// revealed, 2 mines in proximity, not selected
const uint16_t PROGMEM number2Grid[16][16] = {
    { BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK },
    { BLACK, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BLACK },
    { BLACK, BROWN, BROWN, PURPLE, PURPLE, PURPLE, PURPLE, PURPLE, PURPLE, PURPLE, PURPLE, PURPLE, PURPLE, BROWN, BROWN, BLACK },
    { BLACK, BROWN, BROWN, PURPLE, PURPLE, PURPLE, PURPLE, PURPLE, PURPLE, PURPLE, PURPLE, PURPLE, PURPLE, BROWN, BROWN, BLACK },
    { BLACK, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, PURPLE, PURPLE, BROWN, BROWN, BLACK },
    { BLACK, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, PURPLE, PURPLE, BROWN, BROWN, BLACK },
    { BLACK, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, PURPLE, PURPLE, BROWN, BROWN, BLACK },
    { BLACK, BROWN, BROWN, PURPLE, PURPLE, PURPLE, PURPLE, PURPLE, PURPLE, PURPLE, PURPLE, PURPLE, PURPLE, BROWN, BROWN, BLACK },
    { BLACK, BROWN, BROWN, PURPLE, PURPLE, PURPLE, PURPLE, PURPLE, PURPLE, PURPLE, PURPLE, PURPLE, PURPLE, BROWN, BROWN, BLACK },
    { BLACK, BROWN, BROWN, PURPLE, PURPLE, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BLACK },
    { BLACK, BROWN, BROWN, PURPLE, PURPLE, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BLACK },
    { BLACK, BROWN, BROWN, PURPLE, PURPLE, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BLACK },
    { BLACK, BROWN, BROWN, PURPLE, PURPLE, PURPLE, PURPLE, PURPLE, PURPLE, PURPLE, PURPLE, PURPLE, PURPLE, BROWN, BROWN, BLACK },
    { BLACK, BROWN, BROWN, PURPLE, PURPLE, PURPLE, PURPLE, PURPLE, PURPLE, PURPLE, PURPLE, PURPLE, PURPLE, BROWN, BROWN, BLACK },
    { BLACK, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, PURPLE, BROWN, BROWN, BLACK },
    { BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK },
};

// revealed, 2 mines in proximity, but selected
const uint16_t PROGMEM number2SelectedGrid[16][16] = {
    { BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK },

    { BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK },

    { BLACK, BLACK, BROWN, PURPLE, PURPLE, PURPLE, PURPLE, PURPLE, PURPLE, PURPLE, PURPLE, PURPLE, PURPLE, BROWN, BLACK, BLACK },

    { BLACK, BLACK, BROWN, PURPLE, PURPLE, PURPLE, PURPLE, PURPLE, PURPLE, PURPLE, PURPLE, PURPLE, PURPLE, BROWN, BLACK, BLACK },

    { BLACK, BLACK, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, PURPLE, PURPLE, BROWN, BLACK, BLACK },

    { BLACK, BLACK, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, PURPLE, PURPLE, BROWN, BLACK, BLACK },

    { BLACK, BLACK, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, PURPLE, PURPLE, BROWN, BLACK, BLACK },

    { BLACK, BLACK, BROWN, PURPLE, PURPLE, PURPLE, PURPLE, PURPLE, PURPLE, PURPLE, PURPLE, PURPLE, PURPLE, BROWN, BLACK, BLACK },

    { BLACK, BLACK, BROWN, PURPLE, PURPLE, PURPLE, PURPLE, PURPLE, PURPLE, PURPLE, PURPLE, PURPLE, PURPLE, BROWN, BLACK, BLACK },

    { BLACK, BLACK, BROWN, PURPLE, PURPLE, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BLACK, BLACK },

    { BLACK, BLACK, BROWN, PURPLE, PURPLE, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BLACK, BLACK },

    { BLACK, BLACK, BROWN, PURPLE, PURPLE, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BLACK, BLACK },

    { BLACK, BLACK, BROWN, PURPLE, PURPLE, PURPLE, PURPLE, PURPLE, PURPLE, PURPLE, PURPLE, PURPLE, PURPLE, BROWN, BLACK, BLACK },

    { BLACK, BLACK, BROWN, PURPLE, PURPLE, PURPLE, PURPLE, PURPLE, PURPLE, PURPLE, PURPLE, PURPLE, PURPLE, BROWN, BLACK, BLACK },

    { BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK },

    { BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK },
};

// revealed, 3 mines in proximity, not selected
const uint16_t PROGMEM number3Grid[16][16] = {
    { BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK },

    { BLACK, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BLACK },

    { BLACK, BROWN, BROWN, BROWN, BROWN, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BROWN, BROWN, BROWN, BROWN, BLACK },

    { BLACK, BROWN, BROWN, BROWN, BROWN, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BROWN, BROWN, BROWN, BROWN, BLACK },

    { BLACK, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BLUE, BLUE, BROWN, BROWN, BROWN, BROWN, BROWN, BLACK },

    { BLACK, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BLUE, BLUE, BROWN, BROWN, BROWN, BROWN, BROWN, BLACK },

    { BLACK, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BLUE, BLUE, BROWN, BROWN, BROWN, BROWN, BROWN, BLACK },

    { BLACK, BROWN, BROWN, BROWN, BROWN, BLUE, BLUE, BLUE, BLUE, BLUE, BROWN, BROWN, BROWN, BROWN, BROWN, BLACK },

    { BLACK, BROWN, BROWN, BROWN, BROWN, BLUE, BLUE, BLUE, BLUE, BLUE, BROWN, BROWN, BROWN, BROWN, BROWN, BLACK },

    { BLACK, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BLUE, BLUE, BROWN, BROWN, BROWN, BROWN, BROWN, BLACK },

    { BLACK, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BLUE, BLUE, BROWN, BROWN, BROWN, BROWN, BROWN, BLACK },

    { BLACK, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BLUE, BLUE, BROWN, BROWN, BROWN, BROWN, BROWN, BLACK },

    { BLACK, BROWN, BROWN, BROWN, BROWN, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BROWN, BROWN, BROWN, BROWN, BLACK },

    { BLACK, BROWN, BROWN, BROWN, BROWN, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BROWN, BROWN, BROWN, BROWN, BLACK },

    { BLACK, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BLACK },

    { BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK },
};


// revealed, 2 mines in proximity, but selected
const uint16_t PROGMEM number3SelectedGrid[16][16] = {
    { BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK },

    { BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK },

    { BLACK, BLACK, BROWN, BROWN, BROWN, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BROWN, BROWN, BROWN, BLACK, BLACK },

    { BLACK, BLACK, BROWN, BROWN, BROWN, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BROWN, BROWN, BROWN, BLACK, BLACK },

    { BLACK, BLACK, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BLUE, BLUE, BROWN, BROWN, BROWN, BROWN, BLACK, BLACK },

    { BLACK, BLACK, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BLUE, BLUE, BROWN, BROWN, BROWN, BROWN, BLACK, BLACK },

    { BLACK, BLACK, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BLUE, BLUE, BROWN, BROWN, BROWN, BROWN, BLACK, BLACK },

    { BLACK, BLACK, BROWN, BROWN, BROWN, BLUE, BLUE, BLUE, BLUE, BLUE, BROWN, BROWN, BROWN, BROWN, BLACK, BLACK },

    { BLACK, BLACK, BROWN, BROWN, BROWN, BLUE, BLUE, BLUE, BLUE, BLUE, BROWN, BROWN, BROWN, BROWN, BLACK, BLACK },

    { BLACK, BLACK, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BLUE, BLUE, BROWN, BROWN, BROWN, BROWN, BLACK, BLACK },

    { BLACK, BLACK, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BLUE, BLUE, BROWN, BROWN, BROWN, BROWN, BLACK, BLACK },

    { BLACK, BLACK, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BLUE, BLUE, BROWN, BROWN, BROWN, BROWN, BLACK, BLACK },

    { BLACK, BLACK, BROWN, BROWN, BROWN, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BROWN, BROWN, BROWN, BLACK, BLACK },

    { BLACK, BLACK, BROWN, BROWN, BROWN, BLUE, BLUE, BLUE, BLUE, BLUE, BLUE, BROWN, BROWN, BROWN, BLACK, BLACK },

    { BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK },

    { BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK },
};


// revealed, 3 mines in proximity, not selected
const uint16_t PROGMEM flagGrid[16][16] = {
    // TODO: Add number 3 graphic data
    { BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK },

    { BLACK, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BLACK },

    { BLACK, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, RED, BLACK, BROWN, BROWN, BROWN, BROWN, BROWN, BLACK },

    { BLACK, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, RED, RED, BLACK, BROWN, BROWN, BROWN, BROWN, BROWN, BLACK },

    { BLACK, BROWN, BROWN, BROWN, BROWN, BROWN, RED, RED, RED, BLACK, BROWN, BROWN, BROWN, BROWN, BROWN, BLACK },

    { BLACK, BROWN, BROWN, BROWN, RED, RED, RED, RED, RED, BLACK, BROWN, BROWN, BROWN, BROWN, BROWN, BLACK },

    { BLACK, BROWN, BROWN, BROWN, BROWN, RED, RED, RED, RED, BLACK, BROWN, BROWN, BROWN, BROWN, BROWN, BLACK },

    { BLACK, BROWN, BROWN, BROWN, BROWN, BROWN, RED, RED, RED, BLACK, BROWN, BROWN, BROWN, BROWN, BROWN, BLACK },
    
    { BLACK, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, RED, RED, BLACK, BROWN, BROWN, BROWN, BROWN, BROWN, BLACK },

    { BLACK, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, RED, BLACK, BROWN, BROWN, BROWN, BROWN, BROWN, BLACK },

    { BLACK, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BLACK, BROWN, BROWN, BROWN, BROWN, BROWN, BLACK },

    { BLACK, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BLACK, BROWN, BROWN, BROWN, BROWN, BROWN, BLACK },

    { BLACK, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BLACK, BROWN, BROWN, BROWN, BROWN, BROWN, BLACK },

    { BLACK, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BLACK, BROWN, BROWN, BROWN, BROWN, BROWN, BLACK },

    { BLACK, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BLACK, BROWN, BROWN, BROWN, BROWN, BROWN, BLACK },

    { BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK },
};

// revealed, 3 mines in proximity, not selected
const uint16_t PROGMEM flagSelectedGrid[16][16] = {
    { BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK },

    { BLACK, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BLACK },

    { BLACK, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, RED, BLACK, BROWN, BROWN, BROWN, BROWN, BROWN, BLACK },

    { BLACK, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, RED, RED, BLACK, BROWN, BROWN, BROWN, BROWN, BROWN, BLACK },

    { BLACK, BROWN, BROWN, BROWN, BROWN, BROWN, RED, RED, RED, BLACK, BROWN, BROWN, BROWN, BROWN, BROWN, BLACK },

    { BLACK, BROWN, BROWN, BROWN, RED, RED, RED, RED, RED, BLACK, BROWN, BROWN, BROWN, BROWN, BROWN, BLACK },

    { BLACK, BROWN, BROWN, BROWN, BROWN, RED, RED, RED, RED, BLACK, BROWN, BROWN, BROWN, BROWN, BROWN, BLACK },

    { BLACK, BROWN, BROWN, BROWN, BROWN, BROWN, RED, RED, RED, BLACK, BROWN, BROWN, BROWN, BROWN, BROWN, BLACK },
    
    { BLACK, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, RED, RED, BLACK, BROWN, BROWN, BROWN, BROWN, BROWN, BLACK },

    { BLACK, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, RED, BLACK, BROWN, BROWN, BROWN, BROWN, BROWN, BLACK },

    { BLACK, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BLACK, BROWN, BROWN, BROWN, BROWN, BROWN, BLACK },

    { BLACK, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BLACK, BROWN, BROWN, BROWN, BROWN, BROWN, BLACK },

    { BLACK, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BLACK, BROWN, BROWN, BROWN, BROWN, BROWN, BLACK },

    { BLACK, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BLACK, BROWN, BROWN, BROWN, BROWN, BROWN, BLACK },

    { BLACK, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BLACK, BROWN, BROWN, BROWN, BROWN, BROWN, BLACK },

    { BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK },
};

const uint16_t PROGMEM explosionMine1pxGrid[16][16] = {
    { BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK },
    { BLACK, RED,   RED,   RED,   ORANGE,ORANGE,ORANGE,YELLOW,YELLOW,ORANGE,ORANGE,ORANGE,RED,   RED,   RED,   BLACK },
    { BLACK, RED,   RED,   ORANGE,ORANGE,ORANGE,YELLOW,YELLOW,YELLOW,ORANGE,ORANGE,ORANGE,ORANGE,RED,   RED,   BLACK },
    { BLACK, RED,   ORANGE,ORANGE,ORANGE,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,ORANGE,ORANGE,ORANGE,ORANGE,RED,   BLACK },
    { BLACK, ORANGE,ORANGE,ORANGE,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,ORANGE,ORANGE,ORANGE,ORANGE,BLACK },
    { BLACK, ORANGE,ORANGE,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,ORANGE,ORANGE,ORANGE,BLACK },
    { BLACK, ORANGE,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,ORANGE,ORANGE,BLACK },
    { BLACK, YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,ORANGE,BLACK },
    { BLACK, YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,BLACK },
    { BLACK, ORANGE,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,ORANGE,ORANGE,BLACK },
    { BLACK, ORANGE,ORANGE,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,ORANGE,ORANGE,ORANGE,BLACK },
    { BLACK, ORANGE,ORANGE,ORANGE,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,ORANGE,ORANGE,ORANGE,ORANGE,BLACK },
    { BLACK, RED,   ORANGE,ORANGE,ORANGE,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,ORANGE,ORANGE,ORANGE,ORANGE,RED,   BLACK },
    { BLACK, RED,   RED,   ORANGE,ORANGE,ORANGE,YELLOW,YELLOW,YELLOW,ORANGE,ORANGE,ORANGE,ORANGE,RED,   RED,   BLACK },
    { BLACK, RED,   RED,   RED,   ORANGE,ORANGE,ORANGE,YELLOW,YELLOW,ORANGE,ORANGE,ORANGE,RED,   RED,   RED,   BLACK },
    { BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK }
};

const uint16_t PROGMEM explosionMine2pxGrid[16][16] = {
    { BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK },
    { BLACK, BLACK, RED,   RED,   RED,   ORANGE,ORANGE,ORANGE,YELLOW,YELLOW,ORANGE,ORANGE,ORANGE,RED,   RED,   BLACK },
    { BLACK, BLACK, RED,   ORANGE,ORANGE,ORANGE,YELLOW,YELLOW,YELLOW,ORANGE,ORANGE,ORANGE,ORANGE,RED,   RED,   BLACK },
    { BLACK, BLACK, ORANGE,ORANGE,ORANGE,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,ORANGE,ORANGE,ORANGE,ORANGE,ORANGE,BLACK },
    { BLACK, BLACK, ORANGE,ORANGE,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,ORANGE,ORANGE,ORANGE,BLACK },
    { BLACK, BLACK, ORANGE,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,ORANGE,ORANGE,BLACK },
    { BLACK, BLACK, YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,ORANGE,BLACK },
    { BLACK, BLACK, YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,BLACK },
    { BLACK, BLACK, YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,BLACK },
    { BLACK, BLACK, YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,ORANGE,BLACK },
    { BLACK, BLACK, ORANGE,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,ORANGE,ORANGE,BLACK },
    { BLACK, BLACK, ORANGE,ORANGE,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,ORANGE,ORANGE,ORANGE,BLACK },
    { BLACK, BLACK, ORANGE,ORANGE,ORANGE,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,ORANGE,ORANGE,ORANGE,ORANGE,ORANGE,BLACK },
    { BLACK, BLACK, RED,   ORANGE,ORANGE,ORANGE,YELLOW,YELLOW,YELLOW,ORANGE,ORANGE,ORANGE,ORANGE,RED,   RED,   BLACK },
    { BLACK, BLACK, RED,   RED,   RED,   ORANGE,ORANGE,ORANGE,YELLOW,YELLOW,ORANGE,ORANGE,ORANGE,RED,   RED,   BLACK },
    { BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK }
};